In [215]:
import pandas as pd
order_table = pd.read_csv('orders_table.csv')
order_product = pd.read_csv('order_product.csv')
product_table = pd.read_csv('product_table.csv')
ab_test = pd.read_csv('Samples AB.csv')

In [216]:
# обʼєднаємо всі таблиці в один датафрейм

ab_testing = pd.merge(ab_test, order_table, on='customer_id', how='left')
ab_testing = pd.merge(ab_testing, order_product, on='order_id', how='left')
ab_testing = pd.merge(ab_testing, product_table, on='product_id', how='left')

# перевіряємо результат обʼєднання
ab_testing

,customer_id,test_date,sample_group,order_id,order_date,status,delivery_included,product_id,quantity,product_name,price,manufacturer
0,41199,2023-03-01,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,40698,2023-03-01,1,1008627.0,2023-08-14,Delivered,NaN,1077.0,1.0,Egyptian Cotton Towel Set,1500.0,Effertz-DuBuque
2,40698,2023-03-01,1,1000069.0,2023-01-04,Delivered,NaN,1011.0,1.0,Drone with HD Camera,15000.0,"MacGyver, Gibson and Ledner"
3,40698,2023-03-01,1,1007153.0,2023-02-25,Delivered,NaN,1037.0,1.0,Electric Scooter,12000.0,"Kuphal, Rohan and Emmerich"
4,40698,2023-03-01,1,1006499.0,2023-11-23,Delivered,NaN,1030.0,1.0,Ergonomic Office Chair,5000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
16111,40042,2023-07-01,2,1004519.0,2023-08-28,Delivered,NaN,1005.0,2.0,Breathable Mesh Sneakers,2000.0,"Fisher, Wisoky and Boyle"
16112,40042,2023-07-01,2,1001717.0,2023-11-03,Delivered,NaN,1011.0,7.0,Drone with HD Camera,15000.0,"MacGyver, Gibson and Ledner"
16113,40042,2023-07-01,2,1002569.0,2023-03-01,Delivered,NaN,1057.0,1.0,Waterproof Hiking Boots,3000.0,"Lehner, Osinski and Kling"
16114,40042,2023-07-01,2,1008010.0,2023-04-10,Delivered,False,1006.0,1.0,Wireless Keyboard and Mouse Combo,1500.0,"Erdman, Langworth and Quigley"
16115,40042,2023-07-01,2,1004467.0,2023-08-26,Cancelled,True,1050.0,1.0,Home Theater Soundbar,6000.0,Gutkowski Group

In [217]:
ab_testing['revenue']= ab_testing['quantity']*ab_testing['price']
ab_testing['test_orders']=ab_testing['order_date'].str [:7]
ab_testing=ab_testing[ab_testing['test_date']== '2023-07-01']
ab_testing=ab_testing[ab_testing['test_orders']== '2023-07']
ab_testing

,customer_id,test_date,sample_group,order_id,order_date,status,delivery_included,product_id,quantity,product_name,price,manufacturer,revenue,test_orders
8815,40780,2023-07-01,1,1002816.0,2023-07-20,Shipped,NaN,1025.0,2.0,Leather Wallet,1200.0,Hegmann-Greenholt,2400.0,2023-07
8848,40966,2023-07-01,1,1005145.0,2023-07-24,Delivered,NaN,1013.0,1.0,Nonstick Silicone Baking Mat,400.0,"Lakin, Conn and Larkin",400.0,2023-07
8857,40580,2023-07-01,1,1000382.0,2023-07-01,Shipped,True,1046.0,4.0,Beard Grooming Kit,800.0,"Balistreri, Aufderhar and Watsica",3200.0,2023-07
8883,40489,2023-07-01,1,1000150.0,2023-07-05,Delivered,NaN,1009.0,1.0,Ski Goggles Anti-fog,1500.0,"Wintheiser, Veum and Abshire",1500.0,2023-07
8907,40196,2023-07-01,1,1002839.0,2023-07-18,Delivered,False,1000.0,4.0,Robot Vacuum Cleaner,10000.0,"Parisian, Jacobs and Beer",40000.0,2023-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16079,40612,2023-07-01,2,1002863.0,2023-07-06,Delivered,NaN,1051.0,1.0,Virtual Reality Headset,8000.0,"Bahringer, O'Kon and Zemlak",8000.0,2023-07
16092,40794,2023-07-01,2,1008934.0,2023-07-13,Shipped,NaN,1060.0,7.0,Stainless Steel Cookware Set,4500.0,"Ryan, Howell and Rice",31500.0,2023-07
16097,40953,2023-07-01,2,1006774.0,2023-07-10,Delivered,NaN,1080.0,1.0,Reflective Running Vest,600.0,Towne LLC,600.0,2023-07
16098,40953,2023-07-01,2,1000988.0,2023-07-20,Cancelled,NaN,1041.0,1.0,Hydrating Facial Serum,1200.0,Torphy Inc,1200.0,2023-07
16103,40680,2023-07-01,2,1005500.0,2023-07-09,Delivered,NaN,1019.0,3.0,Womens Denim Jeans,1000.0,Stokes-Kemmer,3000.0,2023-07

In [218]:
ab_testing1=ab_testing[ab_testing['sample_group']==1]
ab_testing1

,customer_id,test_date,sample_group,order_id,order_date,status,delivery_included,product_id,quantity,product_name,price,manufacturer,revenue,test_orders
8815,40780,2023-07-01,1,1002816.0,2023-07-20,Shipped,NaN,1025.0,2.0,Leather Wallet,1200.0,Hegmann-Greenholt,2400.0,2023-07
8848,40966,2023-07-01,1,1005145.0,2023-07-24,Delivered,NaN,1013.0,1.0,Nonstick Silicone Baking Mat,400.0,"Lakin, Conn and Larkin",400.0,2023-07
8857,40580,2023-07-01,1,1000382.0,2023-07-01,Shipped,True,1046.0,4.0,Beard Grooming Kit,800.0,"Balistreri, Aufderhar and Watsica",3200.0,2023-07
8883,40489,2023-07-01,1,1000150.0,2023-07-05,Delivered,NaN,1009.0,1.0,Ski Goggles Anti-fog,1500.0,"Wintheiser, Veum and Abshire",1500.0,2023-07
8907,40196,2023-07-01,1,1002839.0,2023-07-18,Delivered,False,1000.0,4.0,Robot Vacuum Cleaner,10000.0,"Parisian, Jacobs and Beer",40000.0,2023-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11826,40325,2023-07-01,1,1005964.0,2023-07-22,Cancelled,NaN,1047.0,1.0,Insulated Water Bottle,600.0,Little-Kulas,600.0,2023-07
11841,40379,2023-07-01,1,1007639.0,2023-07-31,Delivered,NaN,1089.0,1.0,Designer Table Lamp,2000.0,Cummings Inc,2000.0,2023-07
11850,40521,2023-07-01,1,1002907.0,2023-07-31,Delivered,NaN,1030.0,1.0,Ergonomic Office Chair,5000.0,NaN,5000.0,2023-07
11862,40377,2023-07-01,1,1004831.0,2023-07-14,Delivered,False,1043.0,1.0,Cold Press Juicer,4500.0,"Hoppe, Heaney and King",4500.0,2023-07
11865,40614,2023-07-01,1,1000909.0,2023-07-28,Shipped,False,1001.0,1.0,Silk Scarf,700.0,"Keeling, Fritsch and Mohr",700.0,2023-07

In [219]:
test_sample_1 = ab_testing1.groupby('customer_id')['revenue'].mean()
test_sample_1_filled = test_sample_1.fillna(0)
test_sample_1_filled

customer_id
40002     1500.0
40011      800.0
40032     1000.0
40033    25000.0
40037     7000.0
          ...
40981     5000.0
40987     1500.0
40988     8000.0
40992     4000.0
40994     4000.0
Name: revenue, Length: 175, dtype: float64

In [220]:
ab_testing2=ab_testing[ab_testing['sample_group']==2]
ab_testing2

,customer_id,test_date,sample_group,order_id,order_date,status,delivery_included,product_id,quantity,product_name,price,manufacturer,revenue,test_orders
11889,40264,2023-07-01,2,1005043.0,2023-07-31,Delivered,NaN,1010.0,1.0,Tablet 10 64GB,8000.0,"Connelly, Schmidt and Prohaska",8000.0,2023-07
11891,40264,2023-07-01,2,1000021.0,2023-07-17,Delivered,False,1038.0,1.0,Aromatherapy Essential Oil Diffuser,1500.0,Gerhold LLC,1500.0,2023-07
11892,40264,2023-07-01,2,1000021.0,2023-07-17,Delivered,False,1046.0,1.0,Beard Grooming Kit,800.0,"Balistreri, Aufderhar and Watsica",800.0,2023-07
11893,40264,2023-07-01,2,1000021.0,2023-07-17,Delivered,False,1021.0,1.0,Climbing Harness Kit,3000.0,Mann-Rau,3000.0,2023-07
11900,40090,2023-07-01,2,1008879.0,2023-07-13,Delivered,NaN,1069.0,1.0,Designer Sunglasses,4000.0,Lang-Wunsch,4000.0,2023-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16079,40612,2023-07-01,2,1002863.0,2023-07-06,Delivered,NaN,1051.0,1.0,Virtual Reality Headset,8000.0,"Bahringer, O'Kon and Zemlak",8000.0,2023-07
16092,40794,2023-07-01,2,1008934.0,2023-07-13,Shipped,NaN,1060.0,7.0,Stainless Steel Cookware Set,4500.0,"Ryan, Howell and Rice",31500.0,2023-07
16097,40953,2023-07-01,2,1006774.0,2023-07-10,Delivered,NaN,1080.0,1.0,Reflective Running Vest,600.0,Towne LLC,600.0,2023-07
16098,40953,2023-07-01,2,1000988.0,2023-07-20,Cancelled,NaN,1041.0,1.0,Hydrating Facial Serum,1200.0,Torphy Inc,1200.0,2023-07
16103,40680,2023-07-01,2,1005500.0,2023-07-09,Delivered,NaN,1019.0,3.0,Womens Denim Jeans,1000.0,Stokes-Kemmer,3000.0,2023-07

In [221]:
test_sample_2 = ab_testing2.groupby('customer_id')['revenue'].mean()
# Заміна NaN на 0
test_sample_2_filled = test_sample_2.fillna(0)
test_sample_2_filled

customer_id
40003     1940.000000
40006    25000.000000
40016     1200.000000
40017     2150.000000
40018     5000.000000
             ...
40993        0.000000
40996     4500.000000
40997     4283.333333
40998     3500.000000
40999     2400.000000
Name: revenue, Length: 240, dtype: float64

In [222]:
# Вирівнювання розмірів груп
min_length = min(len(test_sample_1_filled), len(test_sample_2_filled))
test_data1 = test_sample_1_filled.iloc[:min_length]
test_data2 = test_sample_2_filled.iloc[:min_length]

In [223]:
test_data1

customer_id
40002     1500.0
40011      800.0
40032     1000.0
40033    25000.0
40037     7000.0
          ...
40981     5000.0
40987     1500.0
40988     8000.0
40992     4000.0
40994     4000.0
Name: revenue, Length: 175, dtype: float64

In [224]:
test_data2

customer_id
40003     1940.0
40006    25000.0
40016     1200.0
40017     2150.0
40018     5000.0
          ...
40736    20000.0
40738     7000.0
40743     8000.0
40747     3200.0
40751     1200.0
Name: revenue, Length: 175, dtype: float64

In [225]:
pip install statsmodels

Requirement already satisfied: statsmodels in c:\users\okova\anaconda3\lib\site-packages (0.14.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.18 in c:\users\okova\anaconda3\lib\site-packages (from statsmodels) (1.26.4)
Requirement already satisfied: scipy!=1.9.2,>=1.4 in c:\users\okova\anaconda3\lib\site-packages (from statsmodels) (1.11.4)
Requirement already satisfied: pandas>=1.0 in c:\users\okova\anaconda3\lib\site-packages (from statsmodels) (2.1.4)
Requirement already satisfied: patsy>=0.5.2 in c:\users\okova\anaconda3\lib\site-packages (from statsmodels) (0.5.3)
Requirement already satisfied: packaging>=21.3 in c:\users\okova\anaconda3\lib\site-packages (from statsmodels) (23.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\okova\anaconda3\lib\site-packages (from pandas>=1.0->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\okova\anaconda3\lib\site-packages (from pandas>=1.0->statsmodels) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\okova\anaconda3\lib\site-packages (from pandas>=1.0->statsmodels) (2023.3)
Requirement already satisfied: six in c:\users\okova\anaconda3\lib\site-packages (from patsy>=0.5.2->statsmodels) (1.16.0)

In [226]:
#Генеруємо вибірки з заданими параметрами
sample_1 = test_data1
sample_2 = test_data2

In [227]:
import statsmodels
from statsmodels.stats.weightstats import ztest 
z_st, p_val = ztest(sample_2, sample_1)
print(f'z-статистика склав {round(z_st,2)}')
print(f'Маємо P-value {round(p_val,2)}')

z-статистика склав 0.74
Маємо P-value 0.46

In [228]:
diff = test_data1.values - test_data2.values

from statsmodels.stats.weightstats import DescrStatsW
# Обчислення довірчого інтервалу
if len(diff) > 1:
    conf_int = DescrStatsW(diff).tconfint_mean(alpha=0.05)
    print('95%% confidence interval=[%.4f,%.4f]' % (conf_int[0], conf_int[1]))
else:
    print("Недостатньо даних для обчислення довірчого інтервалу.")

95% confidence interval=[-3157.7691,1489.8431]

In [229]:
#from statsmodels.stats.weightstats import DescrStatsW
#print("95%% confidence interval: [%.4f, %.4f]"
#      %DescrStatsW(sample_2 - sample_1).tconfint_mean(0.05))